export const CharacterFieldTypesEnum = [
  { value: "text", label: "Text" },
  { value: "textarea", label: "Textarea" },
  { value: "number", label: "Number" },
  { value: "select", label: "Select" },
  { value: "select_multiple", label: "Select (multiple)" },
  { value: "boolean", label: "Boolean" },
  { value: "date", label: "Date" },
  { value: "random_table", label: "Random Table" },
  { value: "dice_roll", label: "Dice Roll" },
  { value: "documents_single", label: "Document (single)" },
  { value: "documents_multiple", label: "Documents (multiple)" },
  { value: "images_single", label: "Image (single)" },
  { value: "images_multiple", label: "Images (multiple)" },
  { value: "locations_single", label: "Location (single)" },
  { value: "locations_multiple", label: "Locations (multiple)" },
  { value: "blueprints_single", label: "Blueprint instances (single)" },
  { value: "blueprints_multiple", label: "Blueprint instances (multiple)" },
  { value: "events_single", label: "Events (single)" },
  { value: "events_multiple", label: "Events (multiple)" },
];

export const BlueprintFieldTypesEnum = [
  { value: "text", label: "Text" },
  { value: "textarea", label: "Textarea" },
  { value: "number", label: "Number" },
  { value: "select", label: "Select" },
  { value: "select_multiple", label: "Select (multiple)" },
  { value: "boolean", label: "Boolean" },
  { value: "date", label: "Date" },
  { value: "random_table", label: "Random Table" },
  { value: "dice_roll", label: "Dice Roll" },
  { value: "documents_single", label: "Document (single)" },
  { value: "documents_multiple", label: "Documents (multiple)" },
  { value: "images_single", label: "Image (single)" },
  { value: "images_multiple", label: "Images (multiple)" },
  { value: "locations_single", label: "Location (single)" },
  { value: "locations_multiple", label: "Locations (multiple)" },
  { value: "characters_single", label: "Character (single)" },
  { value: "characters_multiple", label: "Characters (multiple)" },
  { value: "blueprints_single", label: "Blueprint instances (single)" },
  { value: "blueprints_multiple", label: "Blueprint instances (multiple)" },
  { value: "events_single", label: "Events (single)" },
  { value: "events_multiple", label: "Events (multiple)" },
];

export const EntitiesWithTags = [
  "characters",
  "blueprint_instances",
  "documents",
  "calendars",
  "maps",
  "map_pins",
  "graphs",
  "nodes",
  "edges",
  "events",
];

export const MessageTypeOptions = [
  { label: "Character", value: "character" },
  { label: "Narration", value: "narration" },
  { label: "Place", value: "place" },
];

export const MentionableEntites = ["characters", "blueprint_instances", "documents", "maps", "graphs", "words"];

export const EntitiesWithFoldersEnum = ["documents", "maps", "graphs", "calendars", "dictionaries", "random_tables"];

export const PublicEntities = [
  "characters",
  "blueprint_instances",
  "documents",
  "maps",
  "graphs",
  "calendars",
  "dictionaries",
  // "random_tables",
];

export const UserNotificationEntities = [
  "characters",
  "blueprints",
  "blueprint_instances",
  "documents",
  "maps",
  "map_pins",
  "graphs",
  "calendars",
  "events",
  "dictionaries",
  "words",
  "character_fields_templates",
  "tags",
];

export const UserSidebarEntitiesEnabled = [
  "characters",
  "blueprints",
  "documents",
  "maps",
  "graphs",
  "calendars",
  "dictionaries",
  "random_tables",
  "character_fields_templates",
];

export const MiscellaneousSettings = [
  "sort_tags_alphabetically",
  "show_eras_in_calendars",
  "show_eras_in_timelines",
  "show_date_in_event_tooltip_in_calendar",
  "show_date_in_event_tooltip_in_timeline",
];

export const RolePermissionCodes = [
  "create_characters",
  "read_characters",
  "update_characters",
  "delete_characters",
  "create_blueprints",
  "read_blueprints",
  "update_blueprints",
  "delete_blueprints",
  "create_blueprint_instances",
  "read_blueprint_instances",
  "update_blueprint_instances",
  "delete_blueprint_instances",
  "create_documents",
  "read_documents",
  "update_documents",
  "delete_documents",
  "create_maps",
  "read_maps",
  "update_maps",
  "delete_maps",
  "create_map_pins",
  "read_map_pins",
  "update_map_pins",
  "delete_map_pins",
  "create_graphs",
  "read_graphs",
  "update_graphs",
  "delete_graphs",
  "create_calendars",
  "read_calendars",
  "update_calendars",
  "delete_calendars",
  "create_events",
  "read_events",
  "update_events",
  "delete_events",
  "create_dictionaries",
  "read_dictionaries",
  "update_dictionaries",
  "delete_dictionaries",
  "create_words",
  "read_words",
  "update_words",
  "delete_words",
  "create_random_tables",
  "read_random_tables",
  "update_random_tables",
  "delete_random_tables",
  "create_tags",
  "read_tags",
  "update_tags",
  "delete_tags",
  "create_character_fields_templates",
  "read_character_fields_templates",
  "update_character_fields_templates",
  "delete_character_fields_templates",
  "create_assets",
  "read_assets",
  "update_assets",
  "delete_assets",
] as const;
