export const IconEnum = {
  // Item icons
  home: "ph:house" as const,
  character: "ph:user" as const,
  document: "ph:files-light" as const,
  folder: "ph:folder-light" as const,
  map: "ph:map-trifold" as const,
  map_pin: "ph:map-pin-light" as const,
  map_layers: "et:layers" as const,
  board: "ph:graph-light" as const,
  node: "ph:graph-light" as const,
  edge: "ph:graph-light" as const,
  calendar: "ph:calendar-blank-light" as const,
  screen: "fluent:board-24-regular" as const,
  section: "ph:columns" as const,
  timeline: "mdi:timeline-clock-outline" as const,
  event: "ph:flag" as const,
  dictionary: "ph:book-bookmark-light" as const,
  randomtables: "game-icons:perspective-dice-six-faces-random" as const,
  word: "codicon:whole-word" as const,
  alter_names: "ph:arrows-left-right" as const,
  tags: "ph:tag" as const,
  permissions: "ph:key" as const,

  // Auth

  login: "ph:sign-in" as const,
  logout: "ph:sign-out" as const,

  // UI
  active: "ph:article" as const,
  actions: "ph:dots-three-circle" as const,
  add: "ph:plus" as const,
  add_calendar: "ph:calendar-plus-light" as const,
  additional_fields: "ph:textbox" as const,
  archive: "ph:archive" as const,
  card: "ph:cards" as const,
  close: "mdi:close" as const,
  check: "ph:check" as const,
  check_circle: "ph:check-circle" as const,
  family_tree: "ph:tree-structure" as const,
  flow_arrow: "ph:flow-arrow" as const,
  info_circle: "ph:info" as const,
  link: "ph:link" as const,
  unlock: "ph:lock-simple-open" as const,
  loading: "ph:circle-notch" as const,
  edit: "ph:pencil-simple" as const,
  export: "ph:export" as const,
  trash: "ph:trash" as const,
  save: "ph:floppy-disk" as const,
  star: "ph:star" as const,
  drag: "ph:dots-six-vertical" as const,
  chevron_up: "mdi:chevron-up" as const,
  chevron_down: "mdi:chevron-down" as const,
  chevron_left: "mdi:chevron-left" as const,
  chevron_right: "mdi:chevron-right" as const,
  filter: "ph:funnel" as const,
  user: "ph:user" as const,
  users: "ph:users" as const,
  table: "ph:table" as const,
  grid: "ph:grid-four" as const,
  search: "ph:magnifying-glass-light" as const,
  upload: "ph:upload" as const,
  image: "ph:images" as const,
  settings: "ph:gear" as const,
  sort_asc: "ph:sort-descending" as const,
  sort_desc: "ph:sort-ascending" as const,
  menu: "mdi:menu" as const,
  menu_open: "mdi:menu-open" as const,
  error: "ph:warning-circle" as const,
};
